- lib/shared/utils/query-errors.ts
Ignores ConnectorNotConnectedError error in Rainbowkit + Wagmi  that it is frequent but it does not mean a real crash.
https://balancer-labs.sentry.io/issues/5575379331/?project=4506382607712256&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=0
> fix: ignore ConnectorNotConnectedError

- lib/modules/pool/actions/claim/useClaimCallDataQuery.ts
`queryFn` in react queries cannot return undefined but that was happening in `ve8020` pool  where `gaugeService` is undefined
So this fixes these errors: 
https://balancer-labs.sentry.io/issues/5576050491/?project=4506382607712256&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=7
> fix: avoid undefined query data

- lib/shared/utils/query-errors.ts
The new string should also ignore errors like [this one](https://balancer-labs.sentry.io/issues/5576781302/?project=4506382607712256&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=0)
> fix: relax 'Connector not connected' detection rule

- lib/modules/swap/SwapForm.tsx
- lib/modules/swap/SwapProvider.tsx
- lib/modules/transactions/transaction-steps/TransactionStateProvider.tsx
- lib/modules/transactions/transaction-steps/useTransactionSteps.tsx
After swap success, reset url path on modal close instead of pushing redirect.
> fix: Reset path on swap success

- lib/shared/components/errors/GenericError.tsx
- lib/shared/utils/error-filters.ts
- lib/shared/utils/errors.ts
- lib/shared/utils/query-errors.ts
- Although `simulation.query.error` is typed as `Error`, we found a case where we were receiving a plain string. This fix calls `ensureError` to avoid fix related issues and adds shortMessage to improve the error display in the UI. 
- Remove duplicated `isUserRejectedError` function
> fix: improve error handling

- lib/modules/tokens/TokenInput/TokenInput.tsx
**Before** 
Reloading a swap route was validating before the user balances were loaded, that is, skipping input balance validation.
**After**
We trigger validation once the token balances have been loaded:
> fix: validate after loading token balances

- lib/shared/components/errors/SimulationError.tsx
Uses `GenericError` component to display simulation error in remove liquidity flow:
**Before:** 
**After**
> chore: improve simulation error in remove liquidity

- lib/modules/web3/WagmiConfig.tsx
- lib/modules/web3/transports.ts
- lib/shared/services/viem/viem.client.ts
Using the default transports in `viem client` was causing 429 and other issues that are fixed if we use the same `transports` configuration that we use in `wagmi setup`.
> fix: use wagmi transports setup in viem client

- lib/modules/tokens/TokensProvider.tsx
- lib/shared/services/api/apollo-global-data.provider.tsx
- Extend the revalidate time on the tokens query to 20 minutes. New tokens are only rarely, so 20 minutes should plenty of a refresh interval
- Extend the revalidate time on the token prices query to 10 minutes.
- We now load token prices immediately on page load so the server prices are just placeholder
- Fix the fetch policies on the token price query. We had a poll interval, but the `cache-first` policy meant that it would never query the network.
> Longer cache times on token queries, fix fetch policies

- lib/modules/transactions/transaction-steps/useTransactionSteps.tsx
`onSuccessCalled` condition was preventing from calling refetch, for example, when having 2 token approvals in the same action. 
Adding `stepId` to the state fixes the issue.
> fix: use step index in onSuccessCalled

- lib/modules/pool/actions/LiquidityActionHelpers.ts
- lib/modules/pool/actions/add-liquidity/form/AddLiquidityForm.tsx
- lib/modules/pool/actions/add-liquidity/form/TokenInputs.tsx
- lib/modules/pool/actions/add-liquidity/form/TokenInputsWithAddable.tsx
- lib/modules/pool/actions/add-liquidity/form/useProportionalInputs.tsx
Example pool to test: 
`pools/ethereum/cow/0x232a18645c4e33dd64e6925e03da0f0dd77ad003/add-liquidity`
**Before**: 
Opening the addLiquidity url of a pool that requires proportional (gyro or CoW) but does no have liquidity (`totalShares===0`) leads to different errors. 
**After:** 
We show an alert and disable inputs:
> fix: show alert when the pool requires proportional adds but has no liquidity

- lib/modules/pool/actions/add-liquidity/modal/AddLiquidityReceipt.tsx
- lib/modules/transactions/transaction-steps/useTransactionLogsQuery.ts
Fixes error: 
**Hypothesis**:
When a transaction is executed, it may take some time before it is written to the logs. It is usually immediate, but in this case, there might have been a delay. 
**Solution**:
Showing `isLoading` while `blockHash` is undefined, prevents from showing empty receipt data while the logs are being written.
If `blockHash` is defined but `sentTokens` are empty we show an error (this should only happen if the connected `userAddress` is different from the `userAddress` that sent the transaction).
> fix: show error message if sent tokens are empty

- lib/modules/pool/actions/add-liquidity/modal/AddLiquidityModal.tsx
- lib/modules/web3/useOnUserAccountChanged.tsx
The old code was preventing users from loading a receipt page from its url as the `userAddress` was always changing after `isMounted`. 
The new `useOnUserAccountChanged` hook encapsulates the logic and makes sure that a real user account change has happened. 
TODO: 
We should apply the same fix to other flows.
> fix: avoid redirection when openning receipt page from url

- lib/modules/pool/actions/remove-liquidity/modal/RemoveLiquidityModal.tsx
- lib/modules/swap/modal/SwapModal.tsx
We applied this fix for Add flow [here](https://github.com/balancer/frontend-v3/pull/887)
Now we fix the same issues for removes and swaps.
> fix: redirection when loading receipt page (for swaps and removes)

- lib/modules/swap/SwapForm.tsx
I couldn't reproduce it but we have several sentry errors where token is `undefined`:
https://balancer-labs.sentry.io/issues/5621464688/?project=4506382607712256&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D+Cannot+read+properties+of+undefined+%28reading+%27address%27%29&referrer=issue-stream&statsPeriod=7d&stream_index=4
I don't think it is a real bug so I believe it is better to ignore it. If someone reproduces it, then we can try to fix the root cause.
> fix: ignore undefined token in handleTokenSelect

- lib/modules/transactions/transaction-steps/useTxSound.ts
- test/vitest/setup-vitest.tsx
Fixes this scenario: 
You are in a CoW AMM pool and navigate to swaps. 
`window.location.pathname` is not properly updated but `usePathname` is.
> fix: usePathName instead of window to detect CoW urls

- lib/modules/pool/actions/add-liquidity/handlers/ProportionalAddLiquidity.handler.ts
In the proportional add liquidity handler we want to subtract 10 wei from the bptAmount out that is calculated with the SDK helper. This bpt amount is then fed into the stimulation query and ensures that it always works if the user has maxed out one of their token balances. It's possible even with subtracting 10 wei that this could fail. If we see evidence that this is happening often we can increase this buffer up to 100 wei.
> chore: Subtract 10 wei from bptAmount out

- lib/modules/transactions/transaction-steps/useTransactionLogsQuery.ts
Wagmi does not automatically handle disable `useTransaction` when passing an empty transaction `hash`. It thows an error instead: 
https://github.com/wevm/wagmi/blob/fd0e4cac2bdb57cbcdeb62d33560a79d3bd8bb67/packages/core/src/query/getTransaction.ts#L29
This will fix this[kind of sentry issue](https://balancer-labs.sentry.io/issues/5668551307/events/af9797d0950a487da4056eafbfd31ad7/?project=4506382607712256&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=previous-event&statsPeriod=30d&stream_index=4) that we introduced in a recent refactor.
> fix: Disable useTransaction query when txHash is undefined

- lib/modules/pool/PoolList/PoolListFilters.tsx
- lib/modules/pool/PoolList/PoolListLayout.tsx
- lib/shared/components/inputs/SearchInput.tsx
- Remove vertical jank
- Position absolute title with translateY when FilterTags appear
- AnimatePresence filter tags
- Remove vertical jank within popover
- Move reset button inline with the Filter title in the popover to prevent jank within the popover when an item is selected. 
- Filter button improvements
- Remove horizontal jank from filter button: Position absolute the numbered badge which appears within the Filter button, to remove it from the flow and keep the layout from shifting.
- Use a semantic token for styling for easier customization for partners. 
- Enable the filter tags to go wider
- The filter tags now take up all of the available space remaining after the search bar and filter button. This prevents more layout shifts, since wrapping now happens less frequently. 
- Made …
> Remove jank from filter button interactions

- lib/modules/pool/actions/add-liquidity/form/useProportionalInputs.spec.tsx
- lib/modules/pool/actions/add-liquidity/form/useProportionalInputs.tsx
Entering 0.1 or 0.2 Cow was automatically updating the input to 0.099999999999999999 or 0.199999999999999999999999
**Before:** 
https://github.com/user-attachments/assets/023f4c02-a7b5-49b3-9d5b-fbf7ed235b5f
**After:** 
https://github.com/user-attachments/assets/88b64193-7d4a-4235-a7d1-143b006d959f
> fix: avoid auto updates in used entered input in add proportional form

- lib/modules/pool/PoolList/PoolListTable/PoolListTableRow.tsx
- lib/shared/components/tooltips/apr-tooltip/MainAprTooltip.tsx
> fix: CoW APRs

- lib/modules/pool/actions/add-liquidity/AddLiquidityProvider.tsx
- lib/modules/pool/actions/remove-liquidity/RemoveLiquidityProvider.tsx
The add/remove liquidity handler was only re-loading when the pool id changed, but this means that the handler gets set prior to the on chain data queries finishing. Because of this, all adds/removes are calculated using API data, which is very likely stale.
Added `isLoadingOnchainData` and `isLoading` to the dependencies so that it recreates the handler whenever data gets fetched.
> Fix pool balance discrepancy impacting proportional add/remove

- lib/modules/pool/PoolDetail/PoolComposition/PoolComposition.tsx
- lib/modules/pool/PoolDetail/PoolStats/PoolSnapshot/PoolSnapshotValues.tsx
- lib/modules/pool/pool.utils.ts
- lib/modules/tokens/TokensProvider.tsx
when token prices update tvl is recalculated using the updated prices (token balance weights are already recalculated after token prices update)
> fix: (re)calc tvl to get token weight percentages

- lib/modules/pool/actions/add-liquidity/handlers/UnbalancedAddLiquidity.handler.ts
It looks like the issue is fixed in the SDK so the rounding workaround is not needed anymore. 
https://github.com/balancer/b-sdk/issues/326#issuecomment-2286372869
Closes https://github.com/balancer/frontend-v3/issues/665
> chore: remove unbalanced priceImpact amount rounding (now that SDK related issue is fixed)

- app/react-query.provider.tsx
- lib/modules/transactions/RecentTransactionsProvider.tsx
- lib/modules/web3/contracts/useManagedErc20Transaction.ts
- lib/modules/web3/contracts/useManagedSendTransaction.ts
- lib/modules/web3/contracts/useManagedTransaction.ts
- lib/modules/web3/contracts/wagmi-helpers.ts
We found random timeout issues when passing undefined to wagmi's `timeout` option in `waitForTransactionReceipt`:  
https://github.com/wevm/viem/discussions/1351
Using an explicit timeout option seems to work better. 
This PR uses 25 seconds for polygon and 15 seconds for other chains. Given that react query runs 3 retries by default, we will wait a max of: 
polygon: 25 x 4 = 100 seconds
others: 15 x 4 = 60 seconds
before showing this error in the UI and capturing the error in sentry:
> fix: add explicit waitForTransactionReceipt timeouts

- lib/modules/pool/queries/useOnchainUserPoolBalances.ts
In [portofolio provider](https://github.com/balancer/frontend-v3/blob/fix/portfolioBalancesLoading/lib/modules/portfolio/PortfolioProvider.tsx#L90) we can call `useOnchainUserPoolBalances` with different `poolsData` lists so we need to make sure that the last poolsData onchain data has been loaded. 
This fix adds a new `isLoading` parameter for that.
> fix: avoid pool balance overwrites until onchain data is loaded

- lib/modules/pool/actions/add-liquidity/modal/AddLiquidityModal.tsx
- lib/modules/pool/actions/add-liquidity/modal/AddLiquiditySummary.tsx
- lib/modules/pool/actions/add-liquidity/modal/BptOut.tsx
- lib/modules/tokens/TokenRow/BptRow.tsx
- lib/modules/transactions/transaction-steps/receipts/receipt.hooks.ts
- lib/shared/components/modals/TransactionModalHeader.tsx
**TODO**: the same fix must be applied for removes and swaps.
Opening historical receipts from a tx url was broken. 
This PR on top of receiptLogs PR is an initial improvement to make it work. We can make it better but I would do it in a different PR when it this is a priority.
Now when we open a receipt that takes time to be loaded (artificial delay added  for this demo):
https://github.com/user-attachments/assets/385543e9-221c-47ac-ab02-8a8f105181b7
It also fixes the state where the user tries to load an historic receipt connected with a different account than the one that created the transaction:
> fix: receipt states for Add Liquidity

- lib/modules/web3/ChainConfig.tsx
- lib/shared/utils/urls.ts
Fixes an error in wallet connect when using relative urls for rpcs.
`Before`: 
We were getting `Error: Provided URL is not compatible with HTTP connection: /api/rpc/MAINNET` in the connection callback.
> fix: private rpc url with wallet connect

- lib/modules/pool/actions/PoolActionsPriceImpactDetails.tsx
- lib/modules/pool/actions/add-liquidity/form/AddLiquidityForm.tsx
- lib/modules/pool/actions/remove-liquidity/form/RemoveLiquidityForm.tsx
There is a kind of UX bug in add/remove flows where when you change input values the price impact stays the same until the new result is loaded, then it updates the UI value. This is dangerous as the user could think that the price impact is lower than expected by clicking on next too quickly. This PR simply replaces the price impact values with loading states when the query is fetching.
> fix: Display loading states if price impact is loading

- app/(app)/debug/alerts/page.tsx
- lib/modules/pool/actions/add-liquidity/form/AddLiquidityForm.tsx
- lib/modules/pool/actions/remove-liquidity/form/RemoveLiquidityForm.tsx
- lib/modules/pool/actions/stake/StakeForm.tsx
- lib/modules/pool/actions/unstake/UnstakeForm.tsx
- lib/modules/swap/SwapForm.tsx
- lib/modules/web3/useWalletConnectMetadata.tsx
- lib/shared/components/alerts/BalAlertContent.tsx
- lib/shared/components/alerts/SafeAppAlert.tsx
Detects when a user is connected to a Safe Account via Wallet Connect and shows an alert in the main flows. 
It does not show the alert when `isMobile` is true.
Examples:
It does not show the alerts when the user is connected to a Safe Account within the Safe App.
> feat: show Safe App info alert when using Safe Account via WC

- lib/modules/web3/UserAccountProvider.tsx
- lib/modules/web3/useSafeAppConnectionGuard.tsx
**Before**: 
The app is running as a Safe App and a new EOA connection in another tab also changes the active connection in the Safe App tab.
https://github.com/user-attachments/assets/10eb0eb6-c26b-4c3f-80bd-8ee915f39f38
**After**: 
The Safe account is preserved in the Safe App tab.
https://github.com/user-attachments/assets/897d3acd-2e82-4c5d-93d3-2b2c687be860
> fix: preserve Safe App connection after new EOA connections

- app/api/wallet-check/[address]/route.ts
We are capturing [many wallet-check issues](https://balancer-labs.sentry.io/issues/5696445439/events/e2fa7b21bcf14e4b829b911fec10a719/?project=4506382607712256&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=previous-event&sort=freq&statsPeriod=7d&stream_index=0) with this error: 
`Cannot destructure property 'Symbol(Symbol.iterator)' of '(intermediate value)' as it is null.`
so it's not clear what it is happening. 
Manually testing some of the addresses in those issues worked ok. 
This code tries to log the wrong responses  to better understand the issue.
> fix: improve wallet check reponse error detection

- app/api/wallet-check/[address]/route.ts
This should confirm if we are getting 401's as you suspected @garethfuller
> fix: detect response status errors in reputation request

- lib/modules/pool/PoolDetail/PoolHeader/PoolHeader.tsx
- lib/modules/pool/categories/PoolCategories.tsx
- lib/modules/pool/categories/getPoolCategories.ts
Adds multiple text to category badge if the category metadata has a 'value' attribute and 'points' in it's id.
> feat: Add point multiples to categories

- lib/shared/utils/query-errors.ts
- sentry.client.config.ts
1. Updates sentry transaction field with the request url.
2. We were not checking `shouldIgnore` in non fatal errors in the global sentry guard. This should reduce some noise in sentry.
3. Adds a new ignored exception related with wallet connect and metamask.
> fix: improve sentry setup

- lib/modules/web3/UserAccountProvider.tsx
- lib/modules/web3/useSafeAppConnectionGuard.tsx
The `useSafeAppConnectionGuard` was causing issues when connecting outside Safe App (for example with rabby).
This fix adds a new check to make sure that the guard is only executed when running inside `https://app.safe.global`.
> fix: add isSafeApp check to Safe App guard

- lib/modules/portfolio/PortfolioTable/PortfolioTable.tsx
- lib/modules/portfolio/PortfolioTable/PortfolioTableHeader.tsx
- lib/modules/portfolio/PortfolioTable/PortfolioTableRow.tsx
1. spread headers a bit more evenly but keep some room for range aprs (also see 4.)
1. left align 'staking' column
1. add some padding to the sortable header columns so they line out better (the button on hover will stick out a bit but i don't think that matters)
1. reserve some space for range aprs
before:
after:
> fix: update column alignment in portfolio

- lib/shared/components/tables/PaginatedTable.tsx
Fix jumping of the page while the table is fetching new rows.
Before: https://balancerecosystem.slack.com/archives/C05H1NS8Q8L/p1725034983703829
After:
> fix: page jump on load

- lib/modules/pool/PoolDetail/PoolDetail.tsx
- lib/modules/pool/PoolDetail/PoolUserEvents.tsx
- lib/modules/pool/usePoolEvents.tsx
We had a duplicate `GetPoolEventsDocument` query in a nested component. This fix removes the duplicate query and passes the data down through a prop. It also adds the `skip` option to prevent the query running if the user is not connected.
> fix: Remove duplicate pool event queries

- lib/shared/utils/query-errors.ts
Ignore only when injected.js is present.
> fix: ignore Cannot redefine property error in sentry

- lib/modules/tokens/TokenBalancesProvider.tsx
In the swap page, we had a react query "cache" of 30 seconds to reuse cached balances in case the user is switching back and forth between the same chains in the chain selector.
But should use staleTime instead of gcTime so that the balances are not requested again.
This should save some requests and avoid some 429's in edge-cases. 
From https://tkdodo.eu/blog/practical-react-query#the-defaults-explained
> Secondly, there seems to be a bit of confusion between gcTime and staleTime, so let me try to clear that up:
> 
> staleTime: The duration until a query transitions from fresh to stale. As long as the query is fresh, data will always be read from the cache only - no network request will happen! If the query is stale (which per default is: instantly), you will still get data from the …
> fix: use staletime instead of gcTime to avoid extra balance rpc requests

- lib/modules/swap/handlers/AuraBalSwap.handler.ts
- lib/modules/swap/handlers/DefaultSwap.handler.ts
- lib/modules/swap/handlers/LidoWrap.handler.ts
- lib/modules/swap/handlers/NativeWrap.handler.ts
- lib/modules/swap/handlers/Swap.handler.ts
- lib/modules/swap/useSwapSteps.tsx
In production builds the Class.contstructor.name changes, so this was breaking the production conditional.
> fix: Explicitly set swap handler name

- lib/modules/pool/actions/add-liquidity/form/useProportionalInputs.spec.tsx
- lib/modules/pool/actions/add-liquidity/handlers/ProportionalAddLiquidity.handler.ts
- package.json
- pnpm-lock.yaml
Updates proportional add liquidity handler to pass a reference amount in rather than an calculated bptOut to SDK function.
To test try adding liquidity to CoW pools and see if there are any failures that prevent you from adding your max amount of liquidity.
> chore: Update prop adds handler

- app/react-query.provider.tsx
- lib/shared/utils/query-errors.spec.ts
- lib/shared/utils/query-errors.ts
- sentry.client.config.ts
Sentry stack traces are not like native JS ones so we need to convert them into string to be able to use `.includes`
> fix: sentry stack trace detection

- lib/modules/pool/actions/add-liquidity/handlers/NestedAddLiquidity.handler.ts
- lib/modules/pool/actions/add-liquidity/handlers/ProportionalAddLiquidity.handler.ts
- lib/modules/pool/actions/add-liquidity/handlers/UnbalancedAddLiquidity.handler.ts
- lib/modules/pool/actions/remove-liquidity/handlers/NestedProportionalRemoveLiquidity.handler.ts
- lib/modules/pool/actions/remove-liquidity/handlers/NestedSingleTokenRemoveLiquidity.handler.ts
- lib/modules/pool/actions/remove-liquidity/handlers/ProportionalRemoveLiquidity.handler.ts
- lib/modules/pool/actions/remove-liquidity/handlers/RecoveryRemoveLiquidity.handler.ts
- lib/modules/pool/actions/remove-liquidity/handlers/SingleTokenRemoveLiquidity.handler.ts
- lib/modules/swap/handlers/AuraBalSwap.handler.ts
- lib/modules/swap/handlers/DefaultSwap.handler.ts
- lib/modules/web3/transports.ts
- test/anvil/anvil-setup.ts
- test/vitest/setup-integration.ts
**Before:** 
Handlers were using `getDefaultRpcUrl()` which takes the viem's public rpc url. This could lead to errors due to 429s or temporary outages of the public URLs.
**After:** 
Handlers use `getHandlerRpcUrl()`which takes the rpc url from the transports setup, that is, uses private (or fallback) urls, that should be more reliable. 
With this change we should minimize errors like these ones: https://balancer-labs.sentry.io/issues/5763086985/
We are also using private infura url for integration tests (sepolia and polygon) to make them more reliable.
> fix: use rpc url from transports in handlers

- lib/modules/web3/ChainConfig.tsx
Alchemy FRAXTAL rpc url is having problems. Avoid using it until they fix them.
> fix: avoid private rpc url for Fraxtal

- lib/modules/pool/actions/claim/useClaimAllRewardsStep.tsx
- lib/modules/pool/actions/claim/useClaimAllRewardsSteps.tsx
- lib/modules/pool/actions/claim/useClaimCallDataQuery.ts
We were trying to call the `gaugeMint` function for gauges that are not registered and don't have BAL rewards because all gaugeAddresses were being passed in as if they were the same. This PR splits them up into the appropriate groups:
- Gauges you want to claim non bal rewards for, and
- gauges you want to claim bal rewards for.
This isn't a complete full-proof solution because it seems you can also have gauges with BAL rewards where `gaugeMint` also can't be called, but that should be much more rare.
> fix: Don't do mint calls for non bal reward gauges

- lib/modules/pool/actions/LiquidityActionHelpers.ts
- lib/modules/pool/actions/add-liquidity/form/AddLiquidityForm.tsx
- lib/modules/pool/actions/remove-liquidity/form/RemoveLiquidityForm.tsx
- lib/modules/web3/ChainConfig.tsx
- lib/shared/components/alerts/BalAlertLink.tsx
- lib/shared/components/errors/GenericError.tsx
- lib/shared/utils/error-filters.ts
Improves error handling in liquidity forms: 
- Avoids showing price impact error when there is also a simulation query error.
- Detects specific viem network error in generic error component.
- Avoids read-only issues in SDK.
Example of network error in Add form:
Example of Fraxtal error (already fixed) in Add form:
> fix: improve price impact error handling

- app/react-query.provider.tsx
- package.json
- pnpm-lock.yaml
Avoid `placeholderData` option in `queryClient`
> fix: avoid placeholderData option in queryClient

- app/react-query.provider.tsx
- package.json
- pnpm-lock.yaml
Disabled by default by a boolean flag.
> chore: install react query devtools

- app/react-query.provider.tsx
- lib/modules/pool/actions/add-liquidity/useAddLiquidityStep.tsx
- lib/modules/pool/actions/remove-liquidity/useRemoveLiquidityStep.tsx
- lib/modules/swap/useSwapStep.tsx
- lib/modules/web3/contracts/useManagedSendTransaction.ts
- lib/modules/web3/useTenderly.ts
Adds tenderly simulation urls to sentry metadata for the main flows: add, remove and swap (for both simulation and execution errors).
Comment this line to **avoid form input validation**: 
https://github.com/balancer/frontend-v3/blob/feat/sentryTenderlyUrl/lib/modules/swap/SwapProvider.tsx#L535
Swap with token amount in greater than the wallet balance: 
Open the modal and the simulation should fail: 
You will see a "`Sentry capturing query error:`" in the console: 
It should contain a valid tenderly url in `meta.context.extra.tenderlyUrl`.
If sentry capturing was enabled (disabled by default in dev) you would see an issue like this one:  
https://balancer-labs.sentry.io/issues/5837469276
Then you can open the tenderly url and simulate from the sentry issue 🎈
> feat: add tenderly urls to sentry metadata

- lib/shared/utils/query-errors.ts
By mistake I included the Error type in the `startsWith` string
> fix: some ignored errors detection pattern

- lib/modules/pool/actions/unstake/UnstakeProvider.tsx
- lib/modules/portfolio/PortfolioClaim/useBalRewards.tsx
- lib/modules/portfolio/PortfolioClaim/useClaimableBalances.ts
- lib/modules/web3/contracts/useManagedErc20Transaction.ts
- lib/modules/web3/contracts/useManagedSendTransaction.ts
- lib/modules/web3/contracts/useManagedTransaction.ts
- lib/modules/web3/contracts/wagmi-helpers.ts
- lib/shared/components/modals/ActionModalFooter.tsx
- lib/shared/utils/queries.ts
The reason of this PR is explained in this comment: https://github.com/balancer/frontend-v3/pull/1082/files#diff-513339dcf8a351b65d33cd277aa6442c85248d22a53b788aa262c7e2e5fddb36R34
This was previously solved with `placeholderData` option in the `queryClient` but that was causing other issues, so we had to remove that setup. 
**How to reproduce:** 
Example with `Claim and Unstake` flow 
You can reproduce it in `main branch` if you have something to claim in a staked pool in **polygon**
1. Remove this code from` react-query.provider.tsx` (it was causing other issues and it will be deleted as part of the current PR)
```ts
queryClient.setDefaultOptions({
queries: {
/* Avoids problems in simulation and build queries when the user navigates away from the page while waiting for a tx …
```
> fix: avoid unwanted background simulation refetches

- app/(app)/pools/[chain]/[variant]/[id]/add-liquidity/[[...txHash]]/layout.tsx
- lib/modules/pool/PoolDetail/PoolHeader/PoolBadges.tsx
- lib/modules/pool/PoolDetail/PoolHeader/PoolHeader.tsx
- lib/modules/pool/PoolDetail/PoolMyLiquidity.tsx
- lib/modules/pool/PoolList/usePoolListQueryState.tsx
- lib/modules/pool/pool.types.ts
- lib/modules/pool/pool.utils.ts
* displays Xave's fxpools on pool list
* displays fx pool data and stats
* links to Xave's interface to add/remove liquidity
Some data is still not correctly displayed, like the pool swap fee apr, pool owner, and pool attribute immutability. Using the swap interface also does not route through these pools.
However, these inaccuracies where also present in the frontend-v2 UI.
> feat: enable fx pools

- .github/workflows/checks.yml
- app/api/rpc/[chain]/route.ts
- test/anvil/anvil-setup.ts
Using NEXT prefix simplifies setup of vitest integration tests.
Note the name of the env var in github secrets remains the same (`PRIVATE_ALCHEMY_KEY`)
> chore: rename PRIVATE_ALCHEMY_KEY to NEXT_PRIVATE_ALCHEMY_KEY

- app/react-query.provider.tsx
- lib/modules/pool/actions/remove-liquidity/RemoveLiquidityProvider.tsx
- lib/shared/components/errors/GenericError.tsx
- lib/shared/utils/query-errors.ts
Remove liquidity fixes: 
- Disables next button when there's no amount out
- Disables queries when tokenOut is not defined as it should always exists if there are tokens in the pool. This should fix [this sentry issue](https://balancer-labs.sentry.io/issues/5718946329/?project=4506382607712256) or give us more clues about the real root cause. 
- Improves error handling  (tenderly urls and alert when we get `An unknown RPC error occurred.`)
> fix: remove liquidity fixes

- lib/shared/components/icons/StarIcon.tsx
- lib/shared/components/tooltips/apr-tooltip/MainAprTooltip.tsx
1.  Added new light and dark mode sparkles colors
2. Added new 'Single star' to display pool's with swap fees only
3. Single star icon
- Assigned new single star icon `StarIcon.tsx` to display only when a pool has no other yield beyond swap fees. 
- Use the gray colors already defined in the `defaultGrad`
4. Gray sparkles icon
- This icon with the usual 3 stars should be assigned to any pool with yield in addition to swap fees, but with no staking yield. 
5. Orange sparkles
- This will now only be used to denote pools with staking incentives (could be BAL or other staking incentives)
6. Gold sparkles icon
- Bring back the gold sparkles icon for the BAL / WETH 80/20 pool (it got lost with the recent API update)
> Update sparkles star system to differentiate between different yield types

- lib/modules/pool/actions/add-liquidity/queries/useAddLiquidityPriceImpactQuery.ts
also show the price impact for add liquidity when there is no wallet connected
> fix: show pi for add liquidity w/o connected wallet

- lib/modules/pool/actions/add-liquidity/AddLiquidityProvider.tsx
- lib/modules/pool/actions/remove-liquidity/RemoveLiquidityProvider.tsx
- lib/modules/pool/pool.helpers.spec.ts
- lib/modules/pool/pool.helpers.ts
Extracts `getPoolTokens` function to get a list of `GqlToken[]` from `pool.poolTokens`
- The new function keeps the `supportsNestedActions` feature
- Excludes top level BPT token
- Filters undefined values
These changes fix 2 issues: 
Pool example: pools/ethereum/v2/0xdacf5fa19b1f720111609043ac67a9818262850c000000000000000000000635/add-liquidity
**Before**: 
**After**:
> fix: filter undefined tokens from getPoolTokens

- lib/modules/pool/actions/add-liquidity/modal/AddLiquidityModal.tsx
- lib/modules/pool/actions/remove-liquidity/RemoveLiquidityProvider.tsx
- lib/modules/pool/actions/remove-liquidity/modal/RemoveLiquidityModal.tsx
- lib/modules/swap/modal/SwapModal.tsx
- lib/shared/components/modals/ActionModalFooter.tsx
Avoids animations and `currentStep?.renderAction()` rendering when opening a historic receipt as it was causing flickering and other random issues. 
**Before**: (you can see `Switch network to Ethereum` button rendered for some ms)
https://github.com/user-attachments/assets/724261d9-a794-4d7c-b20f-85a80342ba80
**After**:
https://github.com/user-attachments/assets/39f5730b-4a57-404f-afaf-805871f8e8d0
Fixes other random issues that I couldn't consistently reproduce.
> fix: receipt animations

- lib/modules/pool/actions/add-liquidity/modal/AddLiquidityModal.tsx
- lib/modules/pool/actions/remove-liquidity/RemoveLiquidityProvider.tsx
- lib/modules/pool/actions/remove-liquidity/modal/RemoveLiquidityModal.tsx
- lib/modules/swap/modal/SwapModal.tsx
- lib/modules/web3/contracts/useManagedSendTransaction.ts
- lib/modules/web3/contracts/wagmi-helpers.ts
- lib/shared/components/modals/ActionModalFooter.tsx
It looks like we are affected by this unresolved issue: 
https://github.com/wevm/viem/discussions/1351
Passing undefined timeout works better in my last tests. 
Note that I will keep `getWaitForReceiptTimeout(chainId: number)` function returning undefined to centralise the comment and to be able to change it in the future when we have more info.
For now, I will monitor if this change reduces the Timeout errors in sentry ([example](https://balancer-labs.sentry.io/issues/5842315702/?project=4506382607712256))
> fix: receipt timeouts

- lib/modules/pool/alerts/usePoolAlerts.spec.tsx
- lib/modules/pool/alerts/usePoolAlerts.tsx
- lib/modules/pool/pool.helpers.ts
> feat: add extra pool alerts

- lib/shared/components/errors/GenericError.tsx
- lib/shared/utils/error-filters.ts
- lib/shared/utils/query-errors.ts
Ignores sentry error and shows custom error message when catching a `paused` error.
Can be tested in pool `pools/ethereum/v2/0xdb1f2e1655477d08fb0992f82eede0053b8cd3820000000000000000000006ae/add-liquidity`
**Before**: 
**After**:
> chore: handle BAL#402 (paused) error

- .env.template
- .github/workflows/checks.yml
- app/api/rpc/[chain]/route.ts
- lib/modules/web3/ChainConfig.tsx
You can test that nested add/remove simulation now works in gnosis pools:
https://frontend-v3-git-fix-gnosisdrpc-balancer.vercel.app/pools/gnosis/v2/0x66888e4f35063ad8bb11506a6fde5024fb4f1db0000100000000000000000053/add-liquidity
> fix: use DRPC private url in gnosis

- lib/modules/pool/actions/remove-liquidity/RemoveLiquidityProvider.tsx
- lib/modules/transactions/transaction-steps/TransactionStateProvider.tsx
Two small fixes: 
- enforce pool redirection when closing removal modal after success
- avoid updating transaction if it's already successful
> fix: enforce pool redirection when closing removal modal after success

- .github/workflows/checks.yml
- app/(app)/pools/page.tsx
- lib/modules/transactions/transaction-steps/receipts/receipt.hooks.integration.spec.ts
– Replace CoW Galxe Quest banner with Cow is live banner
> Change promo banners to 'CoW is Live'

- lib/modules/pool/actions/add-liquidity/form/useMaximumInputs.tsx
The API is not currently not returning `0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee`  native tokens for sepolia: 
```
query {
tokenGetTokens(chains: [SEPOLIA]) {
address
}
}
That breaks maximize feature in sepolia.
```
**Before**: 
**After**:
> fix: maximize liquidity in sepolia

- lib/modules/web3/ChainConfig.tsx
- lib/shared/components/errors/GenericError.tsx
- lib/shared/utils/error-filters.ts
We were having problems with Alchemy that should be fixed with dRPC.
Also adds a custom error message when 429 is detected (it should be a rare one):
> fix: setup private RPC urls for fraxtal and mode

- lib/modules/pool/actions/remove-liquidity/RemoveLiquidityProvider.tsx
- lib/modules/pool/actions/remove-liquidity/form/RemoveLiquidityForm.tsx
- lib/shared/components/inputs/InputWithSlider/InputWithSlider.tsx
- lib/shared/components/tooltips/TooltipWithTouch.tsx
fixes #1096 
- block remove liquidity when single asset withdraw is >25% of pool balance
Note: I added the warning as a `disabledReason` first so I created a TooltipWithTouch component to get the tooltips to show on mobile. However PK asked me to move the warning msg closer to the input but still keep the tooltips available on mobile in the remove-liquidity flow. So keep that change here or take it out and do another PR for it?
> feat: update block remove liquidity

- .github/actions/setup/action.yml
- .github/workflows/checks.yml
- lib/modules/pool/__mocks__/getPoolMock.ts
- package.json
- pnpm-lock.yaml
- test/anvil/anvil-global-setup.ts
- test/anvil/anvil-setup.ts
Some improvements that should make integration tests more reliable:
- Use node 20 in GHA CI 
- Bump viem/wagmi/rainbowkit
- Some test function refactors
> chore: use node 20 in github actions

- app/(app)/debug/page.tsx
- app/(app)/debug/pools/page.tsx
- app/(app)/debug/revoke-relayer-approval/page.tsx
- lib/modules/tokens/approvals/useTokenApprovalSteps.tsx
The edge case code was not working as expected. This PR  fixes the tricky management of the double approval transaction `isCompleted` state with parallel hooks.
Can be tested impersonating with the user (0x6Ed0DEBC4C1b36aD558f2801a0F5a49B5a8BA08d) of this sentry error:
https://balancer-labs.sentry.io/issues/5737650083/?project=4506382607712256
> fix: USDT approval edge case

- lib/shared/components/errors/GenericError.tsx
- lib/shared/utils/error-filters.ts
- lib/shared/utils/query-errors.ts
Ignores error and displays specific alert when the user does not have enough gas to complete the transaction:
> chore: add not enough gas error to generic error

- lib/modules/pool/actions/PoolActionsPriceImpactDetails.tsx
- lib/modules/pool/actions/add-liquidity/modal/AddLiquiditySummary.tsx
Example use case: 
Trying to see how much veBAL I would get depositing vs. swapping.
> feat: show LP tokens in add form details
