balancer/frontend-v3

app/(app)/portfolio/[chain]/page.tsx
app/(app)/portfolio/layout.tsx
lib/modules/portfolio/PortfolioClaim/ClaimNetworkPools/ClaimNetworkBlock.tsx
lib/modules/portfolio/PortfolioClaim/ClaimNetworkPools/ClaimNetworkPools.tsx
lib/modules/portfolio/PortfolioClaim/useProtocolRewards.ts
lib/modules/portfolio/PortfolioProvider.tsx

- Fixes bug where protocol rewards don't display if you only have a vebal position.
- Prevents rewards loading in before whole portfolio is loaded.
- Adds loading state to rewards section
- Staggers loading in animation of reward sections.

fix: Reward loading

---

lib/modules/portfolio/PortfolioTable/PortfolioTableRow.tsx
lib/shared/components/tooltips/apr-tooltip/AuraAprTooltip.tsx

feat: enable aura apr

---

lib/modules/pool/PoolDetail/PoolInfo/PoolAttributes/useFormattedPoolAttributes.tsx

This pr adds amp factor in pool details

feat: add amp factor in pool details

---

package.json
pnpm-lock.yaml

chore: update wagmi and rainbow kit

---

app/(app)/pools/cow/CowFooter.tsx
lib/modules/marketing/useEcosystemPoolActivity.tsx
lib/modules/pool/PoolDetail/PoolActivityChart/usePoolActivityChart.tsx
lib/modules/pool/PoolDetail/PoolMyLiquidity.tsx
lib/modules/pool/PoolDetail/PoolStats/PoolSnapshot/PoolSnapshot.tsx
lib/modules/pool/PoolDetail/PoolStats/PoolSnapshot/UserSnapshotValues.tsx
lib/modules/tokens/TokenRow/TokenRow.tsx
lib/shared/components/imgs/CowSandPattern.tsx
lib/shared/components/zen/ZenGarden.tsx
lib/shared/hooks/useBreakpoints.tsx
lib/shared/services/chakra/themes/base/components.ts
lib/shared/services/chakra/themes/cow/colors.ts
lib/shared/services/chakra/themes/cow/tokens.ts

- Applies updated cow theme updates
- Adds Cow Marks to pool composition chart background
- Button colors
- Link colors
- Font colors
- Fix tooltip on activity charts appearing outside viewport (as mentioned by CoW team)
- Also fixed this for the Ecosystem Activity chart on the home page. 
- Fix mobile layout issues with the 'My Liquidity section
- Fix zIndex issue with filters popover appearing underneath cow-footer

CoW theme updates

---

lib/modules/pool/PoolProvider.tsx
lib/modules/pool/pool.hooks.ts
test/vitest/setup-vitest.tsx

https://github.com/user-attachments/assets/720579e7-87e0-4b06-9724-e96ec8756726

chore: redirect when a non CoWAMM pool is opened with cow url

---

lib/modules/pool/PoolDetail/PoolActivityChart/usePoolActivityChart.tsx
lib/modules/pool/PoolDetail/PoolStats/PoolCharts/PoolCharts.tsx
lib/modules/pool/PoolDetail/PoolStats/PoolCharts/usePoolCharts.tsx
lib/shared/services/chakra/themes/base/semantic-tokens.ts

This pr change cow volume chart colors and fixes missing bubbles in activity chart

feat: change cow chart colors

---

lib/modules/pool/PoolDetail/PoolActivityChart/usePoolActivityChart.tsx

fix: remove log

---

lib/modules/price-impact/PriceImpactAccordion.tsx

fix: price impact error styles

---

lib/modules/swap/SwapForm.tsx

fix: swap error styles

---

app/(app)/pools/page.tsx
app/(marketing)/layout.tsx
app/(marketing)/risks/page.tsx
lib/assets/css/global.css
lib/modules/pool/PoolList/PoolListLayout.tsx
lib/shared/components/containers/DefaultPageContainer.tsx
lib/shared/components/navs/Navbar.tsx

- Fixes nav with blurred background.
- Introduces hero background to separate featured section from pools.

feat: Style updates

---

lib/modules/pool/PoolList/PoolListTable/PoolListTableRow.tsx
lib/modules/portfolio/PortfolioTable/PortfolioTableRow.tsx
lib/shared/components/tables/PaginatedTable.tsx

- Fix padding on table rows
- Add FadeInView animation on pool rows on pools page and portfolio page

Fix padding and fade in animation of pool list rows

---

lib/modules/tokens/TokensProvider.spec.tsx
lib/shared/services/api/global.graphql
test/data/all-gql-tokens.fake.ts

Merge when production API has `isErc4626`

fix: add isErc4626 to GetTokensQuery

---

lib/modules/pool/PoolList/PoolListFilters.tsx
lib/modules/pool/PoolList/usePoolListQueryState.tsx
lib/shared/components/inputs/MultiSelect.tsx
lib/shared/services/chakra/themes/base/components.ts

Adds a MultiSelect component and uses it for network selection in the pool list filters.

feat: Multi-select component

---

app/(app)/debug/page.tsx
app/(app)/debug/remove-allowance/page.tsx
lib/modules/transactions/transaction-steps/TransactionStepButton.tsx
lib/modules/transactions/transaction-steps/lib.tsx
lib/modules/transactions/transaction-steps/step-tracker/getStepSettings.tsx
lib/modules/transactions/transaction-steps/useSafeAppTransaction.tsx
lib/modules/web3/contracts/useManagedErc20Transaction.ts
lib/modules/web3/contracts/useManagedSendTransaction.ts
lib/modules/web3/contracts/useManagedTransaction.ts
lib/modules/web3/safe.hooks.tsx

Example of Swap running as a Safe App:
https://github.com/user-attachments/assets/2eeb3cdd-7f07-4451-9ebd-f236acd7ecc5

feat: handle Safe transaction hashes when running as a Safe App

---

lib/modules/pool/pool.utils.ts
lib/shared/hooks/useAprTooltip.ts

fix: apr range

---

lib/config/networks/zkevm.ts

This pr fixes wrong zkevm bal token address

fix: zkevm bal token address

---

.lintstagedrc.cjs

when committing only lint changed files which are also staged

fix: lint only staged files

---

lib/modules/pool/actions/PoolActionsLayout.tsx
lib/shared/components/navs/Navbar.tsx

In add/remove liquidity layout, the backdrop for light mode was broken. This PR fixes that and introduces some subtle improvements.

fix: Pool actions backdrop

---

lib/modules/pool/queries/useOnchainUserPoolBalances.ts

This pr fixes critical undefined balance err

fix: critical undefined balance error

---

lib/modules/pool/pool.utils.ts
lib/modules/vebal/useVebalBoost.tsx
lib/shared/components/tooltips/apr-tooltip/MainAprTooltip.tsx
lib/shared/hooks/_mocks_/aprTooltipDataMock.ts
lib/shared/hooks/useAprTooltip.spec.tsx
lib/shared/hooks/useAprTooltip.ts

This pr fixes problems with apr calculations

fix: boosted apr calc

---

lib/modules/pool/queries/useOnchainUserPoolBalances.integration.spec.ts
lib/modules/pool/queries/useOnchainUserPoolBalances.ts
lib/modules/pool/queries/useUserStakedBalance.tsx
lib/modules/pool/queries/useUserUnstakedBalance.tsx

Steps to replicate on production:
1. Go to portfolio page and connect account
2. Change account
3. You should see a full page error

fix: Portfolio error on account change

---

lib/shared/hooks/useAprTooltip.spec.tsx
lib/shared/hooks/useAprTooltip.ts

This pr fixes logic of abs max apr

fix: logic of abs max apr

---

lib/shared/components/tooltips/apr-tooltip/BaseAprTooltip.tsx
lib/shared/components/tooltips/apr-tooltip/MainAprTooltip.tsx
lib/shared/hooks/useAprTooltip.ts

This pr fixes display of bal reward

fix: change vebal boost display logic and bal reward display

---

app/(app)/portfolio/[chain]/page.tsx
lib/modules/pool/PoolName.tsx
lib/modules/pool/actions/claim/ClaimModal.tsx
lib/modules/pool/actions/unstake/useClaimAndUnstakeStep.tsx
lib/modules/portfolio/PortfolioClaim/ClaimNetworkPools/ClaimNetworkBlock.tsx
lib/modules/portfolio/PortfolioClaim/ClaimNetworkPools/ClaimNetworkPools.tsx
lib/modules/portfolio/PortfolioClaim/ClaimProtocolRevenueModal.tsx

- Improved loading animation
- Updated copy in labels
- Sizing tweaks

Minor UI improvements to Portfolio & Claims sections

---

lib/modules/pool/PoolDetail/PoolComposition/PoolComposition.tsx
lib/modules/pool/PoolDetail/PoolWeightCharts/FeaturedPoolWeightChart.tsx
lib/modules/pool/PoolDetail/PoolWeightCharts/PoolWeightChart.tsx
lib/modules/pool/PoolDetail/PoolWeightCharts/PoolWeightChartLegend.tsx

fix: pool weights chart

---

lib/modules/pool/PoolDetail/PoolActivityTable/PoolActivityTableRow.tsx

resolve ens names through mainnet

fix: ens lookup

---

lib/shared/utils/query-errors.ts

Ignores frequent sentry issue from wagmi.

fix: ignore Cannot read properties of undefined from wagmi

---

lib/modules/pool/actions/add-liquidity/form/AddLiquidityForm.tsx

`SafeAppAlert` was accidentally deleted in [this PR](https://github.com/balancer/frontend-v3/pull/1008)

fix: Recover SafeAppAlert component in Add form

---

lib/shared/components/marketing/build/v3/V3VideoTutorial.tsx

Update Youtube tutorial link

---

lib/config/networks/polygon.ts
lib/debug-helpers.ts
lib/modules/transactions/transaction-steps/receipts/receipt.hooks.integration.spec.ts
lib/modules/web3/contracts/useMulticall.integration.spec.ts
test/data/all-gql-tokens.fake.ts

fix: rename matic to pol

---

lib/shared/utils/query-errors.ts

Ignores  https://balancer-labs.sentry.io/issues/5622743248/

chore: ignore extensionPageScript error in sentry

---

lib/modules/pool/pool.helpers.ts
lib/shared/services/api/pool.graphql

Will be used by Proportional v3 Adds.

chore: add isUnbalancedLiquidityDisabled helper

---

app/(app)/debug/layout.tsx
app/(app)/debug/pools/page.tsx

chore: split debug pools in 3 columns (V3, V2 and Cow AMM)
